// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqG0cKF_qdhvRiWMvcY9T0gWV9R4hmtOc',
    appId: '1:155722521233:web:c32a9c706ce803acc9bd30',
    messagingSenderId: '155722521233',
    projectId: 'ludoteca-3be1e',
    authDomain: 'ludoteca-3be1e.firebaseapp.com',
    storageBucket: 'ludoteca-3be1e.appspot.com',
    measurementId: 'G-GLEV5MGPT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTxXf4ZbUGtn77TsLvRoaFtRI16p1SyxE',
    appId: '1:155722521233:android:488babbaad29a14ac9bd30',
    messagingSenderId: '155722521233',
    projectId: 'ludoteca-3be1e',
    storageBucket: 'ludoteca-3be1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXxpsgOn3UIpJNMi1mPCvebOjcqMuZCuo',
    appId: '1:155722521233:ios:6478ed7c181539edc9bd30',
    messagingSenderId: '155722521233',
    projectId: 'ludoteca-3be1e',
    storageBucket: 'ludoteca-3be1e.appspot.com',
    iosBundleId: 'com.example.gremioDeHistorias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXxpsgOn3UIpJNMi1mPCvebOjcqMuZCuo',
    appId: '1:155722521233:ios:3e0af3f0c60d0cedc9bd30',
    messagingSenderId: '155722521233',
    projectId: 'ludoteca-3be1e',
    storageBucket: 'ludoteca-3be1e.appspot.com',
    iosBundleId: 'com.example.gremioDeHistorias.RunnerTests',
  );
}
